/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotsvg

import kotlin.test.Test
import kotlin.test.assertTrue



class GTest {
    @Test fun initialisationNoArgs() {
        val containers = listOf(Group(), Link(), ClipPath(), Defs(), Mask(), Marker(), Pattern())
        for (container in containers) {
            container {
                clip_path: String? = ""
                color_interpolation: String? = ""
                color_rendering: String? = ""
                display: String? = ""
                mask: String? = ""
                pointer_events: String? = ""
            }
            
        }
    }
}
